package md.virtualwaiter.security;

public enum Permission {
  ADMIN_ACCESS,
  SUPERADMIN_ACCESS,
  STAFF_VIEW,
  STAFF_MANAGE,
  MENU_VIEW,
  MENU_MANAGE,
  REPORTS_VIEW,
  AUDIT_VIEW,
  SETTINGS_MANAGE,
  PAYMENTS_MANAGE,
  INVENTORY_MANAGE,
  LOYALTY_MANAGE,
  GUEST_FLAGS_MANAGE,
  MEDIA_MANAGE,
  HALL_PLAN_MANAGE
}
